#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
             agent {
                     docker {
                         image 'maven:3.8.1-adoptopenjdk-11'
                         args '-v /root/.m2:/root/.m2'
                     }
                 }
        stage('Build') {
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}